
'use server';

import { db, auth } from '@/lib/firebase';
import { 
    collection, 
    getDocs, 
    doc, 
    setDoc, 
    updateDoc, 
    deleteDoc,
    serverTimestamp,
    getDoc,
    addDoc
} from 'firebase/firestore';
import { 
    createUserWithEmailAndPassword, 
    deleteUser as deleteAuthUser 
} from 'firebase/auth';
import { z } from 'zod';

// Zod schema for adding a new user
const addUserSchema = z.object({
  firstName: z.string().min(2),
  lastName: z.string().min(2),
  documentNumber: z.string().min(5),
  email: z.string().email(),
  phone: z.string().min(7),
  role: z.enum(["Administrador", "Analista de Tráfico", "Operador de Tráfico"]),
});

// Zod schema for updating a user (password is optional)
const updateUserSchema = addUserSchema.extend({
    id: z.string().optional(),
});


export type UserProfile = {
  uid: string;
  firstName: string;
  lastName: string;
  documentNumber: string;
  email: string;
  phone: string;
  role: "Administrador" | "Analista de Tráfico" | "Operador de Tráfico";
  avatarUrl: string;
  initials: string;
  createdAt: any;
};

const usersCollection = collection(db, 'users');

// Get all user profiles from Firestore
export async function getUsers(): Promise<UserProfile[]> {
  const snapshot = await getDocs(usersCollection);
  return snapshot.docs.map(doc => {
    const data = doc.data();
    return {
      uid: doc.id,
      ...data,
      createdAt: data.createdAt?.toDate(),
    } as UserProfile;
  });
}

// Add a new user profile to Firestore
export async function addUser(data: z.infer<typeof addUserSchema>) {
    // SECURITY NOTE: This function only creates the user profile in Firestore.
    // To enable login, the administrator must MANUALLY create the user in the 
    // Firebase Console (Authentication section) with the same email.
    // This is a common pattern when client-side user creation is disabled for security.

    try {
        const docRefWithSameEmail = await getDocs(collection(db, "users"));
        const existingUser = docRefWithSameEmail.docs.find(doc => doc.data().email === data.email);

        if (existingUser) {
            throw new Error('A user with this email already exists.');
        }

        const initials = (data.firstName[0] + (data.lastName[0] || '')).toUpperCase();
        const avatarUrl = `https://api.dicebear.com/8.x/initials/svg?seed=${data.firstName} ${data.lastName}`;

        // Create the user profile in Firestore. The UID will be generated by Firestore.
        // To associate this with an auth user, you'd typically use the auth UID as the document ID.
        // Since we are decoupling them, we'll let Firestore generate it.
        const docRef = await addDoc(collection(db, "users"), {
            ...data,
            avatarUrl,
            initials,
            createdAt: serverTimestamp(),
        });

        // The UID for this user profile is the ID of the document we just created.
        const uid = docRef.id;

        // In a real scenario, you would now instruct the admin to create the auth user
        // and perhaps have a secondary step to link this Firestore doc to the auth UID.
        // For this app's purpose, we'll assume the email is the link.

        return { success: true, uid };
    } catch (error: any) {
        console.error("Error adding user profile to Firestore: ", error);
        throw new Error(error.message || "Failed to create user profile in the database.");
    }
}


// Update a user's profile in Firestore
export async function updateUser(uid: string, data: z.infer<typeof updateUserSchema>) {
  const userDoc = doc(db, 'users', uid);
  try {
    const updateData: Partial<z.infer<typeof updateUserSchema>> = { ...data };
    delete updateData.id; // Remove id from data object before updating
    await updateDoc(userDoc, updateData);
    return { success: true };
  } catch (error) {
    console.error("Error updating user: ", error);
    throw new Error("Failed to update user profile in the database.");
  }
}

// Delete a user's profile from Firestore
export async function deleteUser(uid: string) {
  const userDoc = doc(db, 'users', uid);
  try {
    await deleteDoc(userDoc);
    console.warn(`User profile ${uid} deleted from Firestore. Remember to delete from Firebase Auth manually.`);
    return { success: true };
  } catch (error) {
    console.error("Error deleting user profile: ", error);
    throw new Error("Failed to delete user profile from the database.");
  }
}
